export const editButton = document.querySelector(".profile__edit-button"),
  addButton = document.querySelector(".profile__add-button"),
  avatarButton = document.querySelector(".profile__avatar-edit"),
  nameSelector = ".profile__name",
  aboutSelector = ".profile__position",
  avatarSelector = ".profile__avatar",
  closeButtonSelector = ".popup__close-button",
  submitButtonSelector = ".popup__submit-button",
  editFormElement = document.forms["edit-form"],
  addFormElement = document.forms["add-form"],
  updateAvatarFormElement = document.forms["update-avatar-form"],
  formSelector = ".popup__form-container",
  addPopupSelector = ".popup_add-form",
  editPopupSelector = ".popup_edit-form",
  updateAvatarPopupSelector = ".popup_update-avatar",
  confirmPopupSelector = ".popup_confirm",
  formInputSelector = ".popup__input",
  cardsElementSelector = ".elements",
  popupImageSelector = '.popup__image',
  popupImageNameSelector = '.popup__image-name',
  elementLikeSelector = '.element__like',
  elementLikeCounterSelector = '.element__like-counter',
  elementLikedClass = 'element__like_liked',
  elementImageSelector = '.element__image',
  elementRemoveSelector = '.element__remove',
  elementRemoveVisibleClass = 'element__remove_visible',
  elementNameSelector = '.element__name',
  elementSelector = '.element',
  escapeCode = 27,
  configObject = {
    inputSelector: ".popup__input",
    submitButtonSelector: ".popup__submit-button",
    inactiveButtonClass: "popup__submit-button_disabled",
    inputErrorSelector: ".popup__input-error",
    inputContainerSelector: ".popup__form-field",
    errorClass: "popup__input-error_active",
  };
